### ISSUE TITLE
inline methord

### ISSUE THREAD

**Issue by kth8384** [yongxin-ms/cron_timer#10]
BaseTimer::Cancel and DoFunc methord should be declared with inline attribute, otherwise, it will be caught error as more than one implication when link.  The IDE is vc2022.

**Comment by yongxin-ms** [comment]
Can you share your error output? The code is fine on my VS2022.

**Comment by kth8384** [comment]
You can try include "cron_timer.h" in two .cpp files, maybe the error will reappear.


14:55:20:460	已启动生成...
14:55:20:610	1>------ 已启动生成: 项目: chan_sim, 配置: Debug x64 ------
14:55:20:780	1>dl_chan_sim_controller.cpp
14:55:24:639	1>ul_chan_sim_controller.cpp
14:55:28:429	1>LINK : 没有找到 E:\Platform\RRC\x64\Debug\chan_sim.exe 或上一个增量链接没有生成它；正在执行完全链接
14:55:28:674	1>ul_chan_sim_controller.obj : error LNK2005: "public: void __cdecl cron_timer::BaseTimer::Cancel(void)" (?Cancel@BaseTimer@cron_timer@@QEAAXXZ) 已经在 dl_chan_sim_controller.obj 中定义
14:55:28:674	1>ul_chan_sim_controller.obj : error LNK2005: "private: void __cdecl cron_timer::BaseTimer::DoFunc(void)" (?DoFunc@BaseTimer@cron_timer@@AEAAXXZ) 已经在 dl_chan_sim_controller.obj 中定义
14:55:28:739	1>E:\Platform\RRC\x64\Debug\chan_sim.exe : fatal error LNK1169: 找到一个或多个多重定义的符号
14:55:28:797	1>已完成生成项目“chan_sim.vcxproj”的操作 - 失败。
14:55:28:810	========== 生成: 0 成功，1 失败，0 最新，0 已跳过 ==========
14:55:28:810	========= 生成 开始于 14:55，并花费了 08.424 秒 ==========

**Comment by yongxin-ms** [comment]
fixed
