### ISSUE TITLE
windows下编译错误

### ISSUE THREAD

**Issue by windflowerly** [yongxin-ms/cron_timer#2]
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(307,16): error C3083: 'chrono': the symbol to the left of a '::' must be a type
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(307,24): error C3083: 'system_clock': the symbol to the left of a '::' must be a type
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(307,38): error C2039: 'time_point': is not a member of 'std'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.28.29333\include\functional(31): message : see declaration of 'std'
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(307,59): error C3646: 'GetCurTime': unknown override specifier
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(307,60): error C2059: syntax error: ')'
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(307,71): error C2238: unexpected token(s) preceding ';'
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(351,8): error C3083: 'chrono': the symbol to the left of a '::' must be a type
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(351,16): error C3083: 'system_clock': the symbol to the left of a '::' must be a type
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(351,30): error C2039: 'time_point': is not a member of 'std'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.28.29333\include\functional(31): message : see declaration of 'std'
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(351,51): error C3646: 'GetCurTime': unknown override specifier
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(351,51): error C2059: syntax error: '('
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(351,69): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(407,8): error C3083: 'chrono': the symbol to the left of a '::' must be a type
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(407,16): error C3083: 'system_clock': the symbol to the left of a '::' must be a type
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(407,30): error C2039: 'time_point': is not a member of 'std'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.28.29333\include\functional(31): message : see declaration of 'std'
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(407,51): error C3646: 'GetCurTime': unknown override specifier
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(407,51): error C2059: syntax error: '('
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(407,69): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(423,8): error C3083: 'chrono': the symbol to the left of a '::' must be a type
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(423,16): error C3083: 'system_clock': the symbol to the left of a '::' must be a type
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(423,30): error C2039: 'time_point': is not a member of 'std'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.28.29333\include\functional(31): message : see declaration of 'std'
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(423,50): error C3646: 'cur_time_': unknown override specifier
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(423,50): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(402,4): error C2065: 'cur_time_': undeclared identifier
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(402,21): error C3083: 'chrono': the symbol to the left of a '::' must be a type
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(402,29): error C3083: 'system_clock': the symbol to the left of a '::' must be a type
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(402,43): error C2039: 'now': is not a member of 'std'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.28.29333\include\functional(31): message : see declaration of 'std'
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(402,1): error C3861: 'now': identifier not found
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(412,25): error C3083: 'chrono': the symbol to the left of a '::' must be a type
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(412,33): error C3083: 'system_clock': the symbol to the left of a '::' must be a type
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(412,47): error C2039: 'now': is not a member of 'std'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.28.29333\include\functional(31): message : see declaration of 'std'
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(412,1): error C3861: 'now': identifier not found
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(414,5): error C2065: 'cur_time_': undeclared identifier
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(414,23): error C3083: 'chrono': the symbol to the left of a '::' must be a type
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(414,31): error C2039: 'milliseconds': is not a member of 'std'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.28.29333\include\functional(31): message : see declaration of 'std'
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(414,1): error C3861: 'milliseconds': identifier not found
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(415,9): error C2065: 'cur_time_': undeclared identifier
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(491,8): error C3083: 'chrono': the symbol to the left of a '::' must be a type
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(491,16): error C3083: 'system_clock': the symbol to the left of a '::' must be a type
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(491,30): error C2039: 'time_point': is not a member of 'std'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.28.29333\include\functional(31): message : see declaration of 'std'
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(491,55): error C3646: 'GetNearestTime': unknown override specifier
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(491,55): error C2059: syntax error: '('
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(491,58): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(564,17): error C3083: 'chrono': the symbol to the left of a '::' must be a type
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(564,25): error C3083: 'system_clock': the symbol to the left of a '::' must be a type
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(564,39): error C2039: 'time_point': is not a member of 'std'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.28.29333\include\functional(31): message : see declaration of 'std'
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(564,49): error C2065: 'time_point': undeclared identifier
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(564,8): error C2923: 'std::map': 'time_point' is not a valid template type argument for parameter '_Kty'
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(564,8): error C2976: 'std::map': too few template arguments
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.28.29333\include\map(75): message : see declaration of 'std::map'
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(433,11): error C2512: 'std::map': no appropriate default constructor available
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.28.29333\include\map(75,1): message : see declaration of 'std::map'
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(438,1): error C2662: 'void std::_Tree<_Traits>::clear(void) noexcept': cannot convert 'this' pointer from 'std::map' to 'std::_Tree<_Traits> &'
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(438,1): message : Reason: cannot convert from 'std::map' to 'std::_Tree<_Traits>'
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(438,4): message : Conversion requires a second user-defined-conversion operator or constructor
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.28.29333\include\xtree(1444,10): message : see declaration of 'std::_Tree<_Traits>::clear'
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(502,25): error C3083: 'chrono': the symbol to the left of a '::' must be a type
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(502,33): error C3083: 'system_clock': the symbol to the left of a '::' must be a type
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(502,47): error C2039: 'now': is not a member of 'std'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.28.29333\include\functional(31): message : see declaration of 'std'
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(502,1): error C3861: 'now': identifier not found
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(505,26): error C2663: 'std::_Tree<_Traits>::begin': 2 overloads have no legal conversion for 'this' pointer
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(505,1): error C3536: 'it': cannot be used before it is initialized
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(505,49): error C2663: 'std::_Tree<_Traits>::end': 2 overloads have no legal conversion for 'this' pointer
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(507,22): error C2530: 'timer_list': references must be initialized
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(508,1): error C3536: 'expire_time': cannot be used before it is initialized
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(512,1): error C3536: 'timer_list': cannot be used before it is initialized
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(514,1): error C3536: 'p': cannot be used before it is initialized
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(518,17): error C2663: 'std::_Tree<_Traits>::erase': 3 overloads have no legal conversion for 'this' pointer
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(528,16): error C2039: 'GetCurTime': is not a member of 'cron_timer::BaseTimer'
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(288): message : see declaration of 'cron_timer::BaseTimer'
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(529,1): error C3536: 't': cannot be used before it is initialized
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(529,21): error C2663: 'std::_Tree<_Traits>::find': 4 overloads have no legal conversion for 'this' pointer
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(530,1): error C3536: 'it': cannot be used before it is initialized
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(530,21): error C2663: 'std::_Tree<_Traits>::end': 2 overloads have no legal conversion for 'this' pointer
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(532,12): error C2663: 'std::_Tree<_Traits>::insert': 3 overloads have no legal conversion for 'this' pointer
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(533,17): error C2663: 'std::_Tree<_Traits>::find': 4 overloads have no legal conversion for 'this' pointer
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(536,12): error C2530: 'l': references must be initialized
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(537,1): error C3536: 'l': cannot be used before it is initialized
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(544,16): error C2039: 'GetCurTime': is not a member of 'cron_timer::BaseTimer'
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(288): message : see declaration of 'cron_timer::BaseTimer'
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(545,1): error C3536: 't': cannot be used before it is initialized
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(545,21): error C2663: 'std::_Tree<_Traits>::find': 4 overloads have no legal conversion for 'this' pointer
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(546,1): error C3536: 'it': cannot be used before it is initialized
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(546,21): error C2663: 'std::_Tree<_Traits>::end': 2 overloads have no legal conversion for 'this' pointer
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(551,12): error C2530: 'l': references must be initialized
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(552,1): error C3536: 'l': cannot be used before it is initialized
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\source\runtime\net\timer.cpp(25,1): error C2144: syntax error: 'void' should be preceded by ';'
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\source\runtime\net\timer.cpp(30,94): error C2039: 'GetNearestTime': is not a member of 'cron_timer::TimerMgr'
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(427): message : see declaration of 'cron_timer::TimerMgr'
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\source\runtime\net\timer.cpp(35,1): error C2039: '__this': is not a member of 'cron_timer::TimerMgr'
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\include\runtime\net\cron_timer.h(427): message : see declaration of 'cron_timer::TimerMgr'
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\source\runtime\net\timer.cpp(30,12): error C2672: 'std::min': no matching overloaded function found
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\source\runtime\net\timer.cpp(35,1): error C2784: '_Ty std::min(std::initializer_list<_Elem>)': could not deduce template argument for 'std::initializer_list<_Elem>' from 'std::chrono::time_point<std::chrono::system_clock,std::chrono::duration<std::chrono::system_clock::rep,std::chrono::system_clock::period>>'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.28.29333\include\utility(76): message : see declaration of 'std::min'
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\source\runtime\net\timer.cpp(35,1): error C2780: '_Ty std::min(std::initializer_list<_Elem>,_Pr)': expects 2 arguments - 1 provided
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.28.29333\include\utility(73): message : see declaration of 'std::min'
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\source\runtime\net\timer.cpp(35,1): error C2780: 'const _Ty &std::min(const _Ty &,const _Ty &) noexcept(<expr>)': expects 2 arguments - 1 provided
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.28.29333\include\utility(65): message : see declaration of 'std::min'
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\source\runtime\net\timer.cpp(35,1): error C2780: 'const _Ty &std::min(const _Ty &,const _Ty &,_Pr) noexcept(<expr>)': expects 3 arguments - 1 provided
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.28.29333\include\utility(56): message : see declaration of 'std::min'
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\source\runtime\net\timer.cpp(35,1): error C3536: 'nearest_timer': cannot be used before it is initialized
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\source\runtime\net\timer.cpp(31,23): error C2664: 'void std::this_thread::sleep_until(const xtime *)': cannot convert argument 1 from 'int' to 'const xtime *'
1>C:\gangtise\gsdk\cpp\gsdk-cpp-source\source\gsdk\source\runtime\net\timer.cpp(31,35): message : Conversion from integral type to pointer type requires reinterpret_cast, C-style cast or function-style cast
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.28.29333\include\thread(150,17): message : see declaration of 'std::this_thread::sleep_until'

**Comment by flybull** [comment]
应该是没定义头文件#include <chrono>, c++ c++11以上

**Comment by yongxin-ms** [comment]
先关了，如果还有问题可以继续提issue讨论，谢谢
