### ISSUE TITLE
请求添加子线程 example

### ISSUE THREAD

**Issue by ariagecheney** [yongxin-ms/cron_timer#3]
根据https://zhuanlan.zhihu.com/p/373800167的`子线程` 实例, 报错如下:
`no matching function for call to ' cron_timer::Timer Mgr::TimerMgr(MyThread::testCronTimerInSubThread()::<lambda() >` 猜测是不支持 lambda 表达式,但是不清楚原因.

复现如下: 在 qt5.12.12 版本里
1. 定义了 MyThread 类
class MyThread : public QThread{
void TestCronTimerInSubThread() ;
void run();
}

2. 重写 run方法
void run(){
TestCronTimerInSubThread();
}

3. 实现TestCronTimerInSubThread方法
void TestCronTimerInSubThread() {
    // 如果你想在子线程中触发定时器事件
    std::shared_ptr<cron_timer::TimerMgr> mgr = std::make_shared<cron_timer::TimerMgr>([&mgr]() {
        if (mgr != nullptr) {
            // 在子线程中触发定时器事件
            mgr->Update();
        }
    });

    mgr->AddTimer("* * * * * *", [](void) {
        // 每秒钟都会执行一次
        Log("1 second cron timer hit");
    });

//  注释了_shutDown 逻辑;
//    while (!_shutDown) {
  //      std::this_thread::sleep_for(std::chrono::milliseconds(100));
    //}

}

4. #include 正常

**Comment by yongxin-ms** [comment]
感谢您提的issue，我最近比较忙，明天我会仔细看下

**Comment by yongxin-ms** [comment]
> 

在子线程中使用crontimer最好的方式是使用消息队列，你的主逻辑应该用一个消息队列来跑，这时候你可以在lamda函数中向主线程抛一个事件。

可以参考下这个：
`
https://github.com/yongxin-ms/asyncio/tree/asio_post/example/8.gproto_test_server/src
`

**Comment by ariagecheney** [comment]
> > 
> 
> lamda表达式是支持的
> 
> 在子线程中使用crontimer最好的方式是使用消息队列，你的主逻辑应该用一个消息队列来跑，这时候你可以在lamda函数中向主线程抛一个事件。
> 
> 可以参考下这个： `https://github.com/yongxin-ms/asyncio/tree/asio_post/example/8.gproto_test_server/src`

这个我得研究研究.  目前使用  你的pr解决了部分问题.
