### ISSUE TITLE
定时器lambda表达式里执行 HTTP请求操作无法响应

### ISSUE THREAD

**Issue by ariagecheney** [yongxin-ms/cron_timer#5]

**Comment by ariagecheney** [comment]
如下:
1.   mgr->AddTimer("1/5 * * * * *",[&](void) {   // doSomething ....    }  );
2. 在 //doSomething处, 如下:
`              obj为一个QJsonObject对象;
                QUrl url = QUrl("http://127.0.0.1:6005/led/energy/addOneOrMoreToEnergyHour");
                QFuture<QByteArray>  resp =  QtConcurrent::run(acquireDataFromServer,url,obj);
                       resp.waitForFinished();
                       QByteArray res = resp.result();
                       qDebug()<<"response: "<<res;`
3.  自行封装一个获取请求体的函数
               ` QByteArray acquireDataFromServer(QUrl url ,QJsonObject body){
                     QString LogInfo;
                    LogInfo.sprintf("%p", QThread::currentThread());
                       qDebug()<<" 函数acquireDataFromServer 所在线程ID为 threadID : "<<LogInfo;
                    QNetworkRequest request(url);
                    request.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
                    QNetworkAccessManager nam;
                     QNetworkReply *reply = nam.post(request, QJsonDocument(body).toJson());
                    while (!reply->isFinished())
                    {
                //        不停地处理事件，让程序保持响应
                        qApp->processEvents();
                    }
                    qDebug()<< "post请求的reply状态： "<<reply->isFinished();
                    QByteArray response_data = reply->readAll();
                        return response_data;
                }`

**Comment by ariagecheney** [comment]
obj为一个QJsonObject对象;
                QUrl url = QUrl("http://127.0.0.1:6005/led/energy/addOneOrMoreToEnergyHour");
                QFuture<QByteArray>  resp =  QtConcurrent::run(acquireDataFromServer,url,obj);
                       resp.waitForFinished();
                       QByteArray res = resp.result();
                       qDebug()<<"response: "<<res;

**Comment by ariagecheney** [comment]
1. 在mgr所持有的lambda表达式里, 发起一个耗时Http请求, 使用了QFuture和QtConcurrent::run, 即`QFuture<QByteArray>的waitForFinished()` ,  经过验证, 无法在lambda表达式是执行 `发起请求`. 
2. 那么如何在lambda表达式里, 设置一个回调,等待其他耗时线程的响应的值呢?

**Comment by yongxin-ms** [comment]
> 

你可以把QFuture<QByteArray>指针通过参数传给lamda表达式，定时器触发的时候检查一下这个指针的状态
给你举个例子：

`
	m_1second_timer = m_event_loop.CallLater(
		std::chrono::seconds(1),
		[this]() {
			OnOneSecondTimer();
		},
		asyncio::RUN_FOREVER);

`

**Comment by ariagecheney** [comment]
> > 
> 
> 你可以把QFuture指针通过参数传给lamda表达式，定时器触发的时候检查一下这个指针的状态 给你举个例子：
> 
> ![image](https://user-images.githubusercontent.com/7688554/203491871-c8f5c600-0a3d-499a-b905-cef9b007f1ef.png)

好的,   按这思路来, 还是很OK的. 
![087EF444](https://user-images.githubusercontent.com/35078844/203898786-b7d302fc-f045-413e-accb-cfe9b4982364.jpg)
