### ISSUE TITLE
启动定时器导致CPU占满100%问题

### ISSUE THREAD

**Issue by ariagecheney** [yongxin-ms/cron_timer#6]
```
std::atomic_bool  _shutDown; // 默认false;
void testInMain(){
     // 创建mgr变量
   mgr.AddTimer( 
  "* * * * * * ", [](void){
// 打印时间
}
while( ! _shutDown ){
  auto nearest_time = xxxx;
 mgr.Update(); 
}

) ; 
}
```
1. 这样一段代码, 导致linux下占用CPU 100%;  在windows下占用较低.   
2. 根据_shutDown来判定最近一次的更新, 持续占用CPU, 这个怎么解决呢?

**Comment by yongxin-ms** [comment]
这只是一个例子，介绍这些接口，在实际应用中可不能这么用，一般来讲，有定时器的场景都要有一个eventloop，你可以参考下这些例子：
https://github.com/yongxin-ms/asyncio/tree/asio_post/example

还有asyncio源码：
https://github.com/yongxin-ms/asyncio/tree/asio_post/include

**Comment by ariagecheney** [comment]
> 这只是一个例子，介绍这些接口，在实际应用中可不能这么用，一般来讲，有定时器的场景都要有一个eventloop，你可以参考下这些例子： https://github.com/yongxin-ms/asyncio/tree/asio_post/example
> 
> 还有asyncio源码： https://github.com/yongxin-ms/asyncio/tree/asio_post/include

好的, 目前已经设定了合适休眠,大大降低了CPU占用率.
