### ISSUE TITLE
设置年月日为当前，小时为过往小时的问题

### ISSUE THREAD

**Issue by RosenYin** [yongxin-ms/cron_timer#8]
如果mgr.AddTimer函数，它的cron表达式如果设置为当前年，当前月，当前日，秒和分都是*，时如果设置成过往时的话，在运行example的时候会先不断运行，然后退出。
比如当前时间为2023年10月27日15时，如果`mgr.AddTimer("* * 16 27 10 2023", [](void) {Log("--------1 second cron timer hit");});`如此设置，执行exmaple的时候会先不断运行这个。

**Comment by RosenYin** [comment]
还有，如果设置为下一分钟每秒触发，它在这个分钟结束后不会触发，只能重新启动程序才会执行

**Comment by yongxin-ms** [comment]
> 还有，如果设置为下一分钟每秒触发，它在这个分钟结束后不会触发，只能重新启动程序才会执行

简单测了下，我这里是在20秒钟之后执行的，你那边是这样么？好像的确是有点问题

**Comment by RosenYin** [comment]
这个触发多久之后貌似不固定，有时候几秒之后执行，有时候隔了40多s

**Comment by RosenYin** [comment]
问下，这个触发时间有随机误差问题解决从哪里开始嘞

**Comment by yongxin-ms** [comment]
> 问下，这个触发时间有随机误差问题解决从哪里开始嘞

可以设置个断点看看，我最近一阵子在忙公司的事情，你有空的话也可以帮忙看看，提个PR啥的

**Comment by yongxin-ms** [comment]
Fixed, 可以测试下效果如何
